# Generated by Django 6.0.6 on 2026-06-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_subscriber', 'New Subscriber'), ('new_like', 'New Like'), ('new_comment', 'New Comment'), ('new_post', 'New Post'), ('new_message', 'New Message'), ('family_invite', 'Family Invite'), ('family_join', 'Family Join'), ('new_host_booking', 'New Host Booking'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('stream_started', 'Stream Started'), ('payout_completed', 'Payout Completed'), ('system', 'System')], max_length=30),
        ),
    ]
