# Generated by Django 6.0.6 on 2026-06-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-quality_score', '-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='like',
            name='is_unlike',
            field=models.BooleanField(default=False, verbose_name='Is Unlike'),
        ),
        migrations.AddField(
            model_name='post',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='post',
            name='unlike_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
