# Generated by Django 6.0.6 on 2026-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestream',
            name='max_viewers',
            field=models.PositiveIntegerField(default=0, help_text='Batas maksimum penonton, 0 berarti tanpa batas.'),
        ),
    ]
