# Generated by Django 6.0.6 on 2026-06-15 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency'), ('bnb', 'BNB (Binance Coin)'), ('usdt', 'USDT (Tether)')], max_length=20),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Setoran (Deposit)'), ('withdrawal', 'Penarikan (Withdrawal)'), ('earning', 'Pendapatan Sesi Privat/Booking'), ('subscription', 'Pendapatan Langganan'), ('fee_deduction', 'Potongan Biaya Layanan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'Dolar AS (USD)'), ('SGD', 'Dolar Singapura (SGD)'), ('IDR', 'Rupiah (IDR)')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('completed', 'Berhasil'), ('failed', 'Gagal')], default='pending', max_length=15)),
                ('reference_id', models.CharField(blank=True, help_text='ID Booking atau Payment Intent terkait', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Catatan admin atau detail transaksi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
