# Generated by Django 6.0.6 on 2026-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_wallettransaction_host_wallettransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdrawal'), ('earning', 'Earning'), ('refund', 'Refund'), ('subscription', 'Subscription Payment'), ('ticket', 'Ticket Purchase'), ('fee_deduction', 'Potongan Biaya Layanan')], max_length=20),
        ),
    ]
