# Generated by Django 6.0.6 on 2026-06-15 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_wallettransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Emoji atau FontAwesome class (e.g., 🌹, 👑)', max_length=10)),
                ('price_idr', models.DecimalField(decimal_places=2, help_text='Harga dalam Rupiah', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'virtual_gifts',
                'ordering': ['price_idr'],
            },
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_idr', models.DecimalField(decimal_places=2, help_text='Total dibayar sender', max_digits=12)),
                ('platform_fee_idr', models.DecimalField(decimal_places=2, help_text='Potongan platform (30%)', max_digits=12)),
                ('net_host_amount_idr', models.DecimalField(decimal_places=2, help_text='Diterima host (70%)', max_digits=12)),
                ('context', models.CharField(default='profile', help_text='Dimana gift ini dikirim (livestream, profile, private_call)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.virtualgift')),
            ],
            options={
                'db_table': 'gift_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
