# Generated by Django 6.0.6 on 2026-06-16 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_virtualgift_gifttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamBounty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_description', models.TextField(help_text="Deskripsi tantangan (misal: 'Nyanyi lagu A')")),
                ('amount_idr', models.DecimalField(decimal_places=2, help_text='Total saldo ditahan', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Respon Host'), ('accepted', 'Diterima & Dikerjakan'), ('completed', 'Selesai (Dana Cair)'), ('rejected', 'Ditolak (Dana Kembali)'), ('failed', 'Gagal Diselesaikan (Dana Kembali)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties_created', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='bounties_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stream_bounties',
                'ordering': ['-created_at'],
            },
        ),
    ]
