# Generated by Django 6.0.6 on 2026-06-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_streambounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualgift',
            name='icon',
            field=models.CharField(help_text='Emoji, FontAwesome class, atau URL Gambar Stiker', max_length=255),
        ),
    ]
