# Generated by Django 6.0.6 on 2026-06-15 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama unik untuk ruangan ini', max_length=100, unique=True, verbose_name='Nama Ruangan')),
                ('description', models.TextField(blank=True, default='', help_text='Deskripsi fasilitas dan detail ruangan', verbose_name='Deskripsi')),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Jumlah maksimum orang yang bisa menggunakan ruangan', verbose_name='Kapasitas')),
                ('location', models.CharField(blank=True, default='', help_text='Lokasi fisik ruangan (misal: Lantai 3, Gedung A)', max_length=200, verbose_name='Lokasi')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif per Jam (Rp)')),
                ('is_active', models.BooleanField(default=True, help_text='Ruangan tersedia untuk di-booking', verbose_name='Aktif')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL gambar ruangan (opsional)', verbose_name='URL Gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Ruangan',
                'db_table': 'booking_rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Tanggal booking', verbose_name='Tanggal')),
                ('start_time', models.TimeField(help_text='Waktu mulai penggunaan ruangan', verbose_name='Jam Mulai')),
                ('duration_hours', models.PositiveIntegerField(default=1, help_text='Lama penggunaan dalam jam (1-8)', verbose_name='Durasi (Jam)')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='confirmed', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', help_text='Catatan tambahan untuk booking ini', verbose_name='Catatan')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Biaya (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room', verbose_name='Ruangan')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
                'db_table': 'bookings',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['room', 'date', 'start_time'], name='idx_booking_room_date_time'), models.Index(fields=['user', '-date'], name='idx_booking_user_date'), models.Index(fields=['status'], name='idx_booking_status')],
            },
        ),
    ]
