# Generated by Django 6.0.6 on 2026-06-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking_room_reservations',
        ),
    ]
