# Generated by Django 6.0.6 on 2026-06-15 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostBookingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_type', models.CharField(choices=[('30m', '1/2 Jam'), ('1h', '1 Jam'), ('3h', '3 Jam'), ('6h', '6 Jam'), ('12h', '12 Jam'), ('24h', '24 Jam'), ('3d', '3 Hari'), ('7d', '7 Hari'), ('14d', '14 Hari'), ('24d', '24 Hari'), ('30d', '30 Hari'), ('3m', '3 Bulan')], max_length=10, verbose_name='Tipe Durasi')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif (Rp)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif (Tersedia)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='booking_rates', to=settings.AUTH_USER_MODEL, verbose_name='Host')),
            ],
            options={
                'verbose_name': 'Host Rate',
                'verbose_name_plural': 'Host Rates',
                'db_table': 'booking_host_rates',
                'ordering': ['price'],
                'unique_together': {('host', 'duration_type')},
            },
        ),
        migrations.CreateModel(
            name='HostBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='Waktu Mulai')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi Host'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='pending', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Catatan/Instruksi Klien')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Biaya (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='host_bookings_received', to=settings.AUTH_USER_MODEL, verbose_name='Host yang Dibooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_bookings_made', to=settings.AUTH_USER_MODEL, verbose_name='Klien/User')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.hostbookingrate', verbose_name='Paket Tarif yang Dipilih')),
            ],
            options={
                'verbose_name': 'Host Booking',
                'verbose_name_plural': 'Host Bookings',
                'db_table': 'booking_host_reservations',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
