# Generated by Django 6.0.6 on 2026-06-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_hostbookingrate_hostbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostbooking',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya Admin (1%)'),
        ),
        migrations.AddField(
            model_name='hostbooking',
            name='app_tax_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pajak Aplikasi (12%)'),
        ),
        migrations.AddField(
            model_name='hostbooking',
            name='currency',
            field=models.CharField(default='IDR', max_length=3, verbose_name='Mata Uang'),
        ),
        migrations.AddField(
            model_name='hostbooking',
            name='net_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Payout Host (77.3%)'),
        ),
        migrations.AddField(
            model_name='hostbooking',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya Lain-lain (2.7%)'),
        ),
        migrations.AddField(
            model_name='hostbooking',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya Layanan (2%)'),
        ),
        migrations.AddField(
            model_name='hostbooking',
            name='validation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya Keabsahan (5%)'),
        ),
        migrations.AddField(
            model_name='hostbookingrate',
            name='currency',
            field=models.CharField(choices=[('IDR', 'Indonesian Rupiah (IDR)'), ('SGD', 'Singapore Dollar (SGD)'), ('USD', 'US Dollar (USD)'), ('MYR', 'Malaysian Ringgit (MYR)'), ('CNY', 'Chinese Yuan (CNY)')], default='IDR', max_length=3, verbose_name='Mata Uang'),
        ),
        migrations.AlterField(
            model_name='hostbooking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Tagihan Klien'),
        ),
        migrations.AlterField(
            model_name='hostbookingrate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif'),
        ),
    ]
