# Generated by Django 6.0.6 on 2026-06-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_hostbooking_admin_fee_hostbooking_app_tax_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostbooking',
            name='is_no_show_cancelled',
            field=models.BooleanField(default=False, verbose_name='Dibatalkan karena No-Show'),
        ),
        migrations.AddField(
            model_name='hostbooking',
            name='location_shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Lokasi Dibagikan'),
        ),
        migrations.AddField(
            model_name='hostbooking',
            name='meeting_location',
            field=models.TextField(blank=True, default='', verbose_name='Lokasi Pertemuan (Offline)'),
        ),
    ]
