# Generated by Django 6.0.6 on 2026-06-15 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_hostbooking_is_no_show_cancelled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_rating_of_host', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rating Klien untuk Host (1-5)')),
                ('host_rating_of_user', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rating Host untuk Klien (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='booking.hostbooking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Booking Rating',
                'verbose_name_plural': 'Booking Ratings',
                'db_table': 'booking_ratings',
            },
        ),
    ]
