# Generated by Django 6.0.6 on 2026-06-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostbooking',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Reschedule'),
        ),
    ]
