# Generated by Django 6.0.6 on 2026-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_hostbooking_reschedule_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostbooking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Menunggu Verifikasi Kripto'), ('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi Host'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='pending', max_length=15, verbose_name='Status'),
        ),
    ]
