# Generated by Django 6.0.6 on 2026-06-16 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_hostbooking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostbooking',
            name='host',
            field=models.ForeignKey(limit_choices_to={'role': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='host_bookings_received', to=settings.AUTH_USER_MODEL, verbose_name='Host yang Dibooking'),
        ),
        migrations.AlterField(
            model_name='hostbookingrate',
            name='host',
            field=models.ForeignKey(limit_choices_to={'role': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='booking_rates', to=settings.AUTH_USER_MODEL, verbose_name='Host'),
        ),
    ]
