# Generated by Django 6.0.6 on 2026-06-16 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_hostbooking_host_alter_hostbookingrate_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostbooking',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai'),
        ),
        migrations.AddIndex(
            model_name='hostbooking',
            index=models.Index(fields=['host', 'start_datetime', 'end_datetime'], name='idx_host_booking_overlap'),
        ),
    ]
