# Generated by Django 6.0.6 on 2026-06-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_hostbooking_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostbooking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Menunggu Verifikasi Kripto'), ('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi Host'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai'), ('disputed', 'Sengketa')], default='pending', max_length=15, verbose_name='Status'),
        ),
    ]
