# Generated by Django 6.0.6 on 2026-06-17 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_hostbooking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostBookingDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='Alasan Sengketa')),
                ('evidence_url', models.URLField(blank=True, default='', verbose_name='Bukti (Opsional)')),
                ('status', models.CharField(choices=[('open', 'Menunggu Keputusan Admin'), ('resolved_host', 'Dimenangkan Host (Dana diteruskan)'), ('resolved_client', 'Dimenangkan Klien (Dana di-Refund)')], default='open', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Catatan Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='booking.hostbooking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pelapor')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'db_table': 'booking_host_disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
