# Generated by Django 6.0.6 on 2026-06-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_hostbookingdispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostbooking',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Mencegah double booking', max_length=255, null=True, unique=True, verbose_name='Idempotency Key'),
        ),
    ]
