# Generated by Django 6.0.6 on 2026-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_hostbooking_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostbooking",
            name="meeting_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="hostbooking",
            name="meeting_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
