# Generated by Django 6.0.6 on 2026-06-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan'), ('U', 'Tidak Dispesifikasikan')], default='U', max_length=1),
        ),
    ]
