# Generated by Django 6.0.6 on 2026-06-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='document_number',
            field=models.CharField(blank=True, default='', help_text='Nomor NIK KTP / Passport', max_length=100),
        ),
    ]
