# Generated by Django 6.0.6 on 2026-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kycdocument_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Tanggal Lahir', null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Nama Lengkap Sesuai ID', max_length=255),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='selfie_file',
            field=models.FileField(blank=True, help_text='Foto Wajah Terbaru (Maks 4 Bulan)', null=True, upload_to='kyc_selfies/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_file',
            field=models.FileField(help_text='Foto KTP/Passport', upload_to='kyc/%Y/%m/'),
        ),
    ]
