# Generated by Django 6.0.6 on 2026-06-15 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kycdocument_birth_date_kycdocument_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='portfolios/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_photos', to='accounts.creatorprofile')),
            ],
            options={
                'db_table': 'creator_photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
