# Generated by Django 6.0.6 on 2026-06-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_creatorphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='subscription_rules',
            field=models.TextField(blank=True, default='', help_text='Syarat dan ketentuan berlangganan kustom oleh Host.'),
        ),
    ]
