# Generated by Django 6.0.6 on 2026-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_creatorprofile_subscription_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='balance_idr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo IDR'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='balance_sgd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo SGD'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='balance_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo USD'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('education', 'Education'), ('music', 'Music'), ('art', 'Art'), ('fitness', 'Fitness'), ('cooking', 'Cooking'), ('gaming', 'Gaming'), ('lifestyle', 'Lifestyle'), ('technology', 'Technology'), ('lesbian', 'Lesbian'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
