# Generated by Django 6.0.6 on 2026-06-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_creatorprofile_balance_idr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='balance_idr',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='balance_sgd',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='balance_usd',
        ),
        migrations.AddField(
            model_name='user',
            name='balance_idr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo IDR'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_sgd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo SGD'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo USD'),
        ),
    ]
