# Generated by Django 6.0.6 on 2026-06-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_creatorprofile_balance_idr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Di-banned dari Booking Sampai'),
        ),
        migrations.AddField(
            model_name='user',
            name='fake_location_strikes',
            field=models.IntegerField(default=0, verbose_name='Strikes Lokasi Palsu'),
        ),
    ]
