# Generated by Django 6.0.6 on 2026-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_booking_banned_until_user_fake_location_strikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_cny',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo CNY'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_myr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo MYR'),
        ),
    ]
