# Generated by Django 6.0.6 on 2026-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_balance_cny_user_balance_myr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Komisi potongan platform untuk Host ini (Minimum 20%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='is_elite_fan',
            field=models.BooleanField(default=False, verbose_name='Langganan Klien Elite'),
        ),
    ]
