# Generated by Django 6.0.6 on 2026-06-16 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contoh: Host Pendatang Baru Terbaik, 1M Views', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='🏆', help_text='Emoji atau URL Ikon Lencana', max_length=255)),
                ('bonus_idr', models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus uang (IDR) saat lencana diberikan', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'host_badges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('bonus_paid', models.BooleanField(default=False, help_text='Apakah bonus IDR sudah dicairkan ke Wallet Host?')),
                ('host', models.ForeignKey(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hostbadge')),
            ],
            options={
                'db_table': 'host_achievements',
                'ordering': ['-awarded_at'],
                'unique_together': {('host', 'badge')},
            },
        ),
    ]
