# Generated by Django 6.0.6 on 2026-06-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_hostbadge_hostachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='is_exclusive_host',
            field=models.BooleanField(default=False, help_text='Host eksklusif yang dibatasi 8 booking/bulan dengan harga premium ($704-$1000)'),
        ),
    ]
