# Generated by Django 6.0.6 on 2026-06-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_creatorprofile_is_exclusive_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='seo_tags',
            field=models.CharField(blank=True, default='', help_text='Kata kunci SEO (pisahkan dengan koma, misal: gamer, cosplay, jakarta)', max_length=255),
        ),
    ]
