# Generated by Django 6.0.6 on 2026-06-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_creatorprofile_seo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_codes',
            field=models.JSONField(blank=True, default=list, help_text='12 Angka pemulihan akun (1-99)'),
        ),
    ]
