# Generated by Django 6.0.6 on 2026-06-16 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_recovery_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostachievement',
            name='host',
            field=models.ForeignKey(limit_choices_to={'role': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('host', 'Host'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=10),
        ),
    ]
