# Generated by Django 6.0.6 on 2026-06-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_hostachievement_host_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_secret_version',
            field=models.IntegerField(default=1, verbose_name='JWT Secret Version (Log out All)'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('balance_usd__gte', 0)), name='balance_usd_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('balance_sgd__gte', 0)), name='balance_sgd_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('balance_idr__gte', 0)), name='balance_idr_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('balance_myr__gte', 0)), name='balance_myr_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('balance_cny__gte', 0)), name='balance_cny_non_negative'),
        ),
    ]
