# Generated by Django 6.0.6 on 2026-06-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_jwt_secret_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='PIN Transaksi (Hashed)'),
        ),
    ]
