# Generated by Django 6.0.6 on 2026-06-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_cookies',
            field=models.BooleanField(default=False, verbose_name='Cookie Consent'),
        ),
    ]
