# Generated by Django 6.0.6 on 2026-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_email_notifications_user_push_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_covers/%Y/%m/'),
        ),
    ]
