# Generated by Django 6.0.6 on 2026-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='chat_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price to unlock chat in IDR. 0 means free or covered by subscription.', max_digits=10),
        ),
    ]
